export type Locale = "en" | "zh";

const zh: Record<string, string> = {
  "IP address": "IP 地址",
  "QA mode: checks are not saved.": "QA 模式：检测记录不会保存。",
  "Enter an IPv4 address": "输入 IPv4 地址",
  "Analyzing IP...": "正在分析 IP…",
  Analyze: "开始分析",
  "Detecting...": "正在检测…",
  "Auto Detect My IP": "自动检测我的 IP",
  "Compare IPs": "对比 IP",
  "Analysis failed": "分析失败",
  "Unable to retrieve IP information.": "无法获取 IP 信息。",
  "Please try again in a moment.": "请稍后重试。",
  Retry: "重试",
  "Unable to detect your IP. You can enter it manually.": "无法自动检测你的 IP，请手动输入。",
  "Invalid IP address": "请输入有效的 IPv4 地址。",
  "Recent Checks": "最近检测",
  "Saved in this browser only": "仅保存在当前浏览器中",
  "No recent checks yet.": "暂无最近检测记录。",
  "Why check your IP?": "为什么要检测 IP？",
  "Account Registration": "账号注册",
  "Check whether your IP may trigger signup verification.": "了解当前 IP 是否可能触发注册验证。",
  "VPN Usage": "VPN 使用",
  "Understand whether your VPN exit IP looks trustworthy.": "判断 VPN 出口 IP 是否具有良好可信度。",
  "Online Security": "网络安全",
  "See how websites may evaluate your network identity.": "了解网站可能如何判断你的网络身份。",
  "Detecting your IP": "正在检测你的 IP",
  "Preparing IP check...": "正在准备 IP 检测…",
  "Querying AbuseIPDB": "正在查询 AbuseIPDB",
  "Checking AbuseIPDB...": "正在检查 AbuseIPDB…",
  "Querying IPinfo": "正在查询 IPinfo",
  "Querying IPinfo...": "正在查询 IPinfo…",
  "Querying Cloudflare": "正在查询 Cloudflare",
  "Querying Cloudflare...": "正在查询 Cloudflare…",
  "Querying IPQualityScore": "正在查询 IPQualityScore",
  "Checking IPQualityScore...": "正在检查 IPQualityScore…",
  "Querying Scamalytics": "正在查询 Scamalytics",
  "Checking Scamalytics...": "正在检查 Scamalytics…",
  "Querying ipapi.is": "正在查询 ipapi.is",
  "Checking ipapi.is...": "正在检查 ipapi.is…",
  "Calculating Trust Score": "正在计算可信评分",
  "Calculating reputation...": "正在计算声誉…",
  "Generating Report": "正在生成报告",
  "Generating recommendations...": "正在生成使用建议…",
  "Analysis complete. Preparing your report...": "分析完成，正在准备报告…",
  "Finishing analysis...": "正在完成分析…",
  "Analysis complete": "分析完成",
  "Analyzing your IP...": "正在分析你的 IP…",
  "Was this result useful?": "这个结果对你有帮助吗？",
  "Feedback is disabled in QA mode.": "QA 模式下反馈功能已停用。",
  Helpful: "有帮助",
  "Not Helpful": "没有帮助",
  "Wrong IP type": "IP 类型不准确",
  "Wrong location": "位置不准确",
  "Score not convincing": "评分缺乏说服力",
  "Missing information": "信息不完整",
  Other: "其他",
  "Thanks for the feedback.": "感谢你的反馈。",
  "IP Health Score": "IP 健康评分",
  "Checked IP": "已检测 IP",
  "Evidence Quality": "证据质量",
  Assessment: "综合评估",
  Reputation: "声誉",
  "Network Quality": "网络质量",
  Compatibility: "兼容性",
  "Network Identity": "网络身份",
  "Sharing Risk": "共享风险",
  Recommendation: "使用建议",
  "Technical Details": "技术详情",
  Confidence: "可信度",
  Reason: "原因",
  Provider: "网络提供商",
  Location: "位置",
  Country: "国家/地区",
  City: "城市",
  Region: "区域",
  Evidence: "判断依据",
  "Risk Score": "风险评分",
  "Risk Level": "风险等级",
  "Abuse History": "滥用记录",
  Status: "状态",
  Available: "可用",
  available: "可用",
  Unavailable: "不可用",
  unavailable: "不可用",
  Pending: "等待分析",
  "Not analyzed": "尚未分析",
  "Not identified": "未识别",
  "Not reported": "未报告",
  Yes: "是",
  No: "否",
  "Bot Signal": "Bot 信号",
  Server: "服务器",
  Datacenter: "数据中心（Datacenter）",
  Hosting: "托管服务",
  Organization: "组织",
  "Abuser Signal": "滥用信号",
  "HTTP Status": "HTTP 状态",
  Connectivity: "连通性",
  Reachable: "可访问",
  Unreachable: "无法访问",
  "Not verified": "未验证",
  "Direct browser check": "浏览器直接检测",
  "Image probe": "图片探测",
  "Browser probe": "浏览器探测",
  "Browser reachability probes.": "通过浏览器探测服务可访问性。",
  "Connectivity probe data is unavailable.": "暂无连通性探测数据。",
  "Network owner and location fields.": "网络归属与位置字段。",
  "Provider reputation fields.": "声誉数据提供方字段。",
  "Secondary reputation provider fields.": "辅助声誉数据提供方字段。",
  "Secondary IP intelligence provider fields.": "辅助 IP 情报数据字段。",
  "Trace available": "Trace 数据可用",
  "Trace, WARP, and consistency signals.": "Trace、WARP 与一致性信号。",
  "Clean Signals": "良好信号",
  "Review Signals": "需复核信号",
  "No clean signals confirmed": "尚无已确认的良好信号",
  "No review signals detected": "未发现需复核信号",
  "Provider and history signals.": "综合数据提供方与历史记录信号。",
  "No sharing evidence available": "暂无共享风险依据",
  "Suitable Usage": "适合使用",
  "May Need Verification": "可能需要额外验证",
  "May Fail Verification": "可能无法通过验证",
  Avoid: "建议避免",
  Browsing: "日常浏览",
  Streaming: "流媒体",
  "Daily accounts": "日常账号使用",
  "Low-risk services": "低风险服务",
  "New account registration": "注册新账号",
  "Important verification": "重要身份验证",
  "Sensitive account changes": "敏感账号操作",
  "Basic browsing only": "仅基础浏览",
  "Existing account login": "登录已有账号",
  "Payment verification": "支付验证",
  "Residential ISP": "住宅宽带（Residential ISP）",
  "Mobile Network": "移动网络（Mobile Network）",
  "Enterprise Network": "企业网络（Enterprise Network）",
  "Public Infrastructure": "公共基础设施（Public Infrastructure）",
  "Cloud Provider": "云服务商（Cloud Provider）",
  "VPN / Proxy": "VPN / 代理（Proxy）",
  "Tor Exit": "Tor 出口节点（Tor Exit）",
  Unknown: "未知",
  High: "高",
  Medium: "中",
  Low: "低",
  "High quality IP": "高质量 IP",
  "Review dimensions": "部分维度需复核",
  "High risk signals": "发现高风险信号",
  "Review Needed": "需要复核",
  "Good Quality": "质量良好",
  "Strong overall IP quality signals.": "整体 IP 质量信号良好。",
  "Some signals may require verification.": "部分信号可能需要进一步验证。",
  "Sensitive services may restrict this IP.": "敏感服务可能会限制此 IP。",
  "Insufficient evidence for a high-confidence verdict.": "现有证据不足以做出高可信度判断。",
  "Good available signals with some data sources unavailable.": "现有信号良好，但部分数据源不可用。",
  "Insufficient evidence for a high-confidence assessment. Important data sources were unavailable: IPQS reputation data was unavailable; Scamalytics was available. Connectivity probes were partially verified.": "证据不足，无法做出高可信度评估。部分重要数据源不可用：IPQS 声誉数据不可用；Scamalytics 可用。连通性探测仅得到部分验证。",
  "Important data sources were unavailable: IPQS reputation data was unavailable; Scamalytics was available. Connectivity probes were partially verified.": "部分重要数据源不可用：IPQS 声誉数据不可用；Scamalytics 可用。连通性探测仅得到部分验证。",
  "Clean Signals, Limited Evidence": "信号良好，但证据有限",
  "Strong Network Quality": "网络质量良好",
  "Moderate Compatibility": "兼容性一般",
  "Clean IP history": "IP 历史记录良好",
  "No abuse history or high reputation provider risk was reported.": "未发现滥用记录，声誉数据提供方也未报告高风险。",
  "IPQS reputation data was unavailable; Scamalytics was available.": "IPQS 声誉数据不可用；Scamalytics 可用。",
  "Network type not fully identified": "网络类型尚未完全识别",
  "Provider data did not clearly identify a residential or infrastructure network.": "数据提供方未能明确判断该 IP 属于住宅网络还是基础设施网络。",
  "IPInfo network ownership data is available.": "IPInfo 网络归属数据可用。",
  "Connectivity not fully verified": "连通性尚未完全验证",
  "Browser probes ran, but reachability could not be fully confirmed.": "浏览器探测已完成，但无法完整确认可访问性。",
  "Some connectivity probes could not be fully verified.": "部分连通性探测无法完整验证。",
  "Public infrastructure detected. This IP appears to support DNS, CDN, edge, or other internet services.": "检测到公共基础设施。此 IP 可能用于 DNS、CDN、边缘节点或其他互联网服务。",
  "IP matches Google Public DNS infrastructure.": "此 IP 与 Google Public DNS 基础设施匹配。",
  "Public DNS, CDN, and edge infrastructure is normal for services, but it is not ideal as a personal browsing or account registration IP.": "公共 DNS、CDN 和边缘基础设施用于服务很正常，但不适合作为个人浏览或注册账号的 IP。",
  "Managed infrastructure pattern": "托管基础设施特征",
  "IP mismatch": "IP 信息不一致",
  "None detected": "未发现",
  "This is normal for public DNS, CDN, and edge infrastructure, but it is not ideal as a personal browsing or account registration IP.": "这类公共 DNS、CDN 和边缘基础设施用于服务很正常，但不适合作为个人浏览或注册账号的 IP。",
  "ASN, IPInfo, IPQS, Scamalytics, ipapi.is, connectivity, and Cloudflare": "ASN、IPInfo、IPQS、Scamalytics、ipapi.is、连通性与 Cloudflare",
  "IP Health provides reputation-based guidance only. Services may also consider account history, device signals, payment method, browser fingerprint, and behavior.": "IP Health 仅提供基于声誉数据的参考建议。服务平台还可能综合账号历史、设备信号、支付方式、浏览器指纹和行为等因素。",
  "Residential ISP detected": "检测到住宅宽带",
  "Network ownership looks like a normal consumer ISP or mobile network.": "网络归属表现为普通消费级 ISP 或移动网络。",
  "Residential ISP detected. This IP appears to belong to a consumer broadband provider.": "检测到住宅宽带。此 IP 可能属于面向消费者的宽带提供商。",
  "This looks like a normal access network and is less likely to be heavily shared.": "这看起来是普通接入网络，被大量用户共享的可能性较低。",
  "No strong privacy or infrastructure signal": "未发现明显的匿名网络或基础设施信号",
  "This looks suitable for normal browsing and account use when reputation is clean. Minor review signals may still trigger extra checks on stricter platforms.": "在 IP 声誉良好时，适合日常浏览和账号使用。轻微复核信号仍可能在风控较严格的平台触发额外检查。",
  "IPQualityScore data is unavailable.": "IPQualityScore 数据不可用。",
  "Scamalytics data is unavailable.": "Scamalytics 数据不可用。",
  "ipapi.is data is unavailable.": "ipapi.is 数据不可用。",
  "Seen by Cloudflare trace.": "由 Cloudflare Trace 检测。",
  "No WARP detected": "未检测到 WARP",
  "Needs review": "需要复核",
  "Network integrity is unavailable right now.": "当前无法获取网络完整性数据。",
  "Tor network detected": "检测到 Tor 网络",
  "VPN or proxy network detected": "检测到 VPN 或代理网络",
  "Cloud or hosting infrastructure detected": "检测到云端或托管基础设施",
  "Enterprise network detected": "检测到企业网络",
  "Public infrastructure detected": "检测到公共基础设施",
  "Minor network review signals": "轻微网络复核信号",
  "Enterprise network review signals": "企业网络复核信号",
  "Regional restriction detected": "检测到区域限制",
  "Connectivity failure detected": "检测到连通性故障",
  "Connectivity verified": "连通性已验证",
  "All tested service probes were reachable.": "所有已测试的服务探测均可访问。",
  "Checking reputation and network identity.": "正在检查 IP 声誉与网络身份。",
  "Reputation Needs Review": "IP 声誉需要复核",
  "High reputation risk detected": "检测到较高声誉风险",
  "Abuse history or reputation provider data raised a strong signal.": "滥用记录或声誉数据提供方报告了强风险信号。",
  "Network identity could not be confidently determined.": "无法可靠判断网络身份。",
  "Sharing level could not be confidently determined.": "无法可靠判断网络共享程度。",
  "Network identity unknown": "网络身份未知",
  "Provider data limited": "数据提供方信息有限",
  "High risk: severe abuse history was reported, so this IP is not recommended for account registration, verification, banking, payments, or sensitive login.": "高风险：检测到严重滥用记录，不建议将此 IP 用于账号注册、身份验证、银行、支付或敏感登录。",
  "Clean IP reputation": "IP 声誉良好",
  "Normal network path": "网络路径正常",
  "Strong compatibility": "兼容性良好",
  "Stable recent checks": "近期检测结果稳定",
  "No major risk signals detected": "未发现明显风险信号",
  "Clean abuse history": "未发现滥用记录",
  "Minor review signal": "轻微复核信号",
  "Enterprise network review": "企业网络复核信号",
  "Public infrastructure": "公共基础设施",
  "Cloud or hosting infrastructure": "云端或托管基础设施",
  "VPN or proxy signal detected": "检测到 VPN 或代理信号",
  "Tor exit signal detected": "检测到 Tor 出口节点信号",
  "Reputation risk signal": "声誉风险信号",
  "Connectivity signal detected": "检测到连通性风险信号",
  "Tor exit traffic is high risk for registration, verification, banking, payments, and sensitive login.": "Tor 出口流量在注册、身份验证、银行、支付及敏感登录场景中通常属于高风险信号。",
  "Some checks may require review, but this is not a strong privacy-network signal by itself.": "部分检测可能需要复核，但这一信号本身并不代表强匿名网络风险。",
  "Large organization and shared corporate networks can receive extra checks on some platforms.": "大型组织或企业共享网络在部分平台上可能触发额外验证。",
  "Normal for services and edge networks, but not ideal as a personal browsing or account registration IP.": "这类网络用于服务或边缘节点很正常，但不适合作为个人浏览或注册账号的 IP。",
  "Some platforms add review steps for shared cloud hosting IP ranges.": "部分平台会对共享云托管 IP 段增加复核步骤。",
  "Many platforms treat hosted infrastructure as less trustworthy than residential ISP traffic.": "许多平台对托管基础设施 IP 的信任度低于住宅宽带 IP。",
  "Some services may request additional verification.": "部分服务可能要求额外验证。",
  "Provider reputation data reported elevated risk.": "声誉数据提供方报告了较高风险。",
  "Some services may be harder to access from this network path.": "通过当前网络路径访问部分服务可能更困难。",
};

export function localizeText(locale: Locale, value: string): string {
  if (locale === "en" || !value) return value;
  if (zh[value]) return zh[value];

  return value
    .replace(/^Confidence: (.+)$/, (_, level) => `可信度：${zh[level] ?? level}`)
    .replace(/^Abuse history: (.+)$/, "滥用记录：$1")
    .replace(/^Low IPQS risk score (.+)$/, "IPQS 风险评分较低：$1")
    .replace(/^IPQS risk score: (.+)$/, "IPQS 风险评分：$1")
    .replace(/^Provider data identifies (.+) as a residential ISP\.$/, "数据提供方将 $1 识别为住宅宽带 ISP。")
    .replace(/^ASN belongs to (.+) infrastructure\.$/, "ASN 属于 $1 基础设施。")
    .replace(/^ASN belongs to (.+) public internet infrastructure\.$/, "ASN 属于 $1 公共互联网基础设施。")
    .replace(/^IPQualityScore reports (\d+)\/100 reputation risk\.$/, "IPQualityScore 报告的声誉风险评分为 $1/100。")
    .replace(/^Scamalytics reports (\d+)\/100 reputation risk\.$/, "Scamalytics 报告的声誉风险评分为 $1/100。")
    .replace(/^(\d+) of (\d+) browser probes were unreachable\.$/, "$2 项浏览器探测中有 $1 项无法访问。")
    .replace(/^(\d+) probes were verified reachable and (\d+) could not be fully verified by the browser\.$/, "已确认 $1 项可访问，另有 $2 项无法由浏览器完整验证。")
    .replace(/Service compatibility probability is (\d+)%\./, "服务兼容概率为 $1%。");
}

export function messages(locale: Locale) {
  return (value: string) => localizeText(locale, value);
}
